### ISSUE TITLE
root biomass

### ISSUE THREAD

**Issue by wwieder** [srearl/soilHarmonization#27]
This is related to #26, but NEON data are provided in mg DW cm^-2 with separate root %C that can be used to convert to gC m^-2, the [target unit for bgb](https://docs.google.com/spreadsheets/d/1NKCZu0wguoFg9ZTwKpWzYwWqKl_Ppal7k8zqGb8fk3Y/edit#gid=433031455). How much other root biomass data to we have from other sites besides NEON?  Are they typically location or profile data?  I wonder if we should revisit how we're handling these data in the key-key?

**Comment by wwieder** [comment]
More confusing now is that Samantha noticed the target units for bgb on the shiny app seem to be kg/m2?  Lot's of errors being thrown for [NEON periodic roots](https://drive.google.com/file/d/1uKL3nFm7CzvPgd4efytnfr3v2EUbP9rf/view?usp=sharing). @srearl, maybe worth a call to brainstorm here?

**Comment by wwieder** [comment]
The bulk of our bgb data are coming from NutNet and NEON, which both report values in gDM/m2 (or mgDM/cm2).  Other sites that treat this similarly are CDR, UMBS DIRT, BOUSSON DIRT.

Exceptions are the AND reference stands, which reported as in mass C units per area

**Comment by wwieder** [comment]
Can we add a units provided for bgb to gDM cm-2 (for Bousson).

**Comment by wwieder** [comment]
Suggesting we move the target for bgb to gDW/m2.  Only two sites HBR and AND provided data in gC/m2.  Let's multiply these by 2 to get back to gDW/m2.  All other sites are already in DW units, but we'll still have to convert to appropriate units for mass and area.

**Comment by srearl** [comment]
Will - I am stuck not being able to test this because of that darn duplicated Google ID or whatever it is that is confounding by connection between R and Google. Please give the branch below a try. We will have to keep in mind that the units conversion update in the script is now out of sync with both the key file version 2 and the key file update script. Also, am super nervous that we are changing the target units at this stage so we really need to be cautious.

https://github.com/srearl/soilHarmonization/tree/units-conversion-update

cc @piersond

**Comment by wwieder** [comment]
Conversions seem to be good.  I hope we can be done using the update key file script.  I think everything should be Key_V2 now.  What does the key file version 2 do?

**Comment by srearl** [comment]
These conversions have been added to the package units conversion table; adding the units as a drop-down in the key file is, likely, a version 3 feature so closing this for now.
